classdef nlos_models
    %NLOS_MODELS Summary of this class goes here
    %   Detailed explanation goes here
    
    properties
        
    end
    
    methods(Static)
        function learner = classification_tree(predictors, response, cv_flag)
            fprintf('Training classication tree... ');
            
            % Train
            if cv_flag
                learner = fitctree(...
                    predictors, ...
                    response, ...
                    'SplitCriterion', 'gdi', ...
                    'MaxNumSplits', 200, ...
                    'Surrogate', 'off', ...
                    'ClassNames', [0; 1], ...
                    'KFold', 10);
            else
                 learner = fitctree(...
                    predictors, ...
                    response, ...
                    'SplitCriterion', 'gdi', ...
                    'MaxNumSplits', 200, ...
                    'Surrogate', 'off', ...
                    'ClassNames', [0; 1]);               
            end
            fprintf('done!\n');
            
        end
        
        function learner = discriminant_linear(predictors, response)
           fprintf('Training linear discriminant analysis model... ');
            
            learner = fitcdiscr(...
                predictors, ...
                response, ...
                'DiscrimType', 'linear', ...
                'Gamma', 0, ...
                'FillCoeffs', 'off', ...
                'ClassNames', [0; 1], ...
                'KFold', 10);    
            
            fprintf('done!\n');

        end
        
        function learner = discriminant_quadratic(predictors, response)
           fprintf('Training linear discriminant analysis model... ');
            
            learner = fitcdiscr(...
                predictors, ...
                response, ...
                'DiscrimType', 'quadratic', ...
                'FillCoeffs', 'off', ...
                'ClassNames', [0; 1], ...
                'KFold', 10);    
            
            fprintf('done!\n');

        end
        
        function learner = knn_euclidean(predictors, response)
            fprintf('Training KNN (K=10) Euclidean model... ');
            
            learner = fitcknn(...
                predictors, ...
                response, ...
                'Distance', 'Euclidean', ...
                'Exponent', [], ...
                'NumNeighbors', 10, ...
                'DistanceWeight', 'Equal', ...
                'Standardize', true, ...
                'ClassNames', [0; 1], ...
                'KFold', 10); 
            
            fprintf('done!\n');
            
        end
        
        function learner = knn_euclidean_SIweight(predictors, response)
            fprintf('Training KNN (K=10) Euclidean model  with SquaredInverse weighing... ');
            
            learner = fitcknn(...
                predictors, ...
                response, ...
                'Distance', 'Euclidean', ...
                'Exponent', [], ...
                'NumNeighbors', 10, ...
                'DistanceWeight', 'SquaredInverse', ...
                'Standardize', true, ...
                'ClassNames', [0; 1], ...
                'KFold', 10); 
            
            fprintf('done!\n');
            
         end
        
        function learner = knn_minkowski(predictors, response)
            fprintf('Training KNN (K=10) Minkowski model... ');
            
            learner = fitcknn(...
                predictors, ...
                response, ...
                'Distance', 'Minkowski', ...
                'Exponent', 3, ...
                'NumNeighbors', 10, ...
                'DistanceWeight', 'Equal', ...
                'Standardize', true, ...
                'ClassNames', [0; 1], ...
                'KFold', 10);
            
            fprintf('done!\n');
            
        end 
        
        function learner = ensemble_bagging(predictors, response)
            
            fprintf('Training Ensemble (Bagging) model... ');
            
            template = templateTree(...
                'MaxNumSplits', 6074);
            
            learner = fitcensemble(...
                predictors, ...
                response, ...
                'Method', 'Bag', ...
                'NumLearningCycles', 30, ...
                'Learners', template, ...
                'ClassNames', [0; 1], ...
                'KFold', 10); 
            
            fprintf('done!\n');
        end
        
        function learner = svm_linear(predictors, response)
            fprintf('Training linear SVM model... ');
            
            learner = fitcsvm(...
               predictors, ...
               response, ...
               'ClassNames',[0; 1], ...
               'Standardize', true, ...
               'KernelFunction','linear', ...
               'KFold', 10);
                
            fprintf('done!\n');
        end
        
        function learner = svm_rbf_auto(predictors, response)
            %Best observed params: 
            %BoxConstraint = 66.802
            %KernelScale = 25.458
            
            fprintf('Training RBF SVM model... ');
            
            learner = fitcsvm(...
               predictors, ...
               response, ...
               'ClassNames',[0; 1], ...
               'KernelFunction','RBF', ...
               'OptimizeHyperparameters','auto', ...
               'HyperparameterOptimizationOptions',struct('AcquisitionFunctionName', 'expected-improvement-plus'));
            
            fprintf('done!\n');
        end  
        
        function learner = svm_rbf(predictors, response)
            fprintf('Training RBF SVM model... ');
            
            learner = fitcsvm(...
               predictors, ...
               response, ...
               'ClassNames',[0; 1], ...
               'Standardize', true, ...
               'KernelFunction','RBF', ...
               'KFold', 10);
            
            fprintf('done!\n');
        end
        
        function learner = svm_rbf2(predictors, response)
            fprintf('Training RBF SVM model 2 ... ');
            
            learner = fitcsvm(...
                predictors, ...
                response, ...
                'KernelFunction', 'RBF', ...
                'PolynomialOrder', [], ...
                'KernelScale', 0.66, ...
                'BoxConstraint', 1, ...
                'Standardize', true, ...
                'ClassNames', [0; 1], ...
                'KFold', 10);
            
            fprintf('done!\n');
        end
        
        function learner = svm_poly2(predictors, response)
            fprintf('Training Polynomial (order 2) SVM model... ');
            
        	learner = fitcsvm(...
                predictors, ...
                response, ...
                'KernelFunction', 'polynomial', ...
                'PolynomialOrder', 2, ...
                'KernelScale', 0.66, ...
                'BoxConstraint', 1, ...
                'Standardize', true, ...
                'ClassNames', [0; 1]);
            
            fprintf('done!\n');
        end
        
        function learner = svm_poly3(predictors, response)
            fprintf('Training Polynomial (order 3) SVM model... ');
            
        	learner = fitcsvm(...
                predictors, ...
                response, ...
                'KernelFunction', 'polynomial', ...
                'PolynomialOrder', 3, ...
                'KernelScale', 0.66, ...
                'BoxConstraint', 1, ...
                'Standardize', true, ...
                'ClassNames', [0; 1]);
            
            fprintf('done!\n');
        end        
        
    end
end

